// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: document.sql

package sqlc

import (
	"context"
)

const createTaskDocument = `-- name: CreateTaskDocument :one
INSERT INTO task_documents (
    task_id,
    file_name,
    file_path
)
VALUES ($1, $2, $3)
RETURNING id, task_id, file_name, file_path, uploaded_at
`

type CreateTaskDocumentParams struct {
	TaskID   int32
	FileName string
	FilePath string
}

func (q *Queries) CreateTaskDocument(ctx context.Context, arg CreateTaskDocumentParams) (TaskDocument, error) {
	row := q.db.QueryRow(ctx, createTaskDocument, arg.TaskID, arg.FileName, arg.FilePath)
	var i TaskDocument
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FileName,
		&i.FilePath,
		&i.UploadedAt,
	)
	return i, err
}

const deleteTaskDocument = `-- name: DeleteTaskDocument :exec
DELETE FROM task_documents
WHERE id = $1
`

func (q *Queries) DeleteTaskDocument(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTaskDocument, id)
	return err
}

const getTaskDocumentByID = `-- name: GetTaskDocumentByID :one
SELECT id, task_id, file_name, file_path, uploaded_at FROM task_documents
WHERE id = $1
`

func (q *Queries) GetTaskDocumentByID(ctx context.Context, id int32) (TaskDocument, error) {
	row := q.db.QueryRow(ctx, getTaskDocumentByID, id)
	var i TaskDocument
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FileName,
		&i.FilePath,
		&i.UploadedAt,
	)
	return i, err
}

const getTaskDocuments = `-- name: GetTaskDocuments :many
SELECT id, task_id, file_name, file_path, uploaded_at FROM task_documents
WHERE task_id = $1
`

func (q *Queries) GetTaskDocuments(ctx context.Context, taskID int32) ([]TaskDocument, error) {
	rows, err := q.db.Query(ctx, getTaskDocuments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDocument
	for rows.Next() {
		var i TaskDocument
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FileName,
			&i.FilePath,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
